name: PlatformIO

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: PlatformIO Run
        uses: karniv00l/platformio-run-action@v1
        with:
          environments: "esp12e"
          targets: "esp12e"
          project-dir: "./"
          project-conf: "./platformio.ini"
          jobs: 6
          silent: false
          verbose: true
          disable-auto-clean: false
